apiVersion: v1
kind: ConfigMap
metadata:
  annotations: {}
  name: nginx-web-conf-cm
data:
  nginx.conf: |
    user nginx;
    worker_processes  1;
    events {
      worker_connections 10240;
    }
    http {
      server {
        listen 8080;
        add_header Access-Control-Allow-Origin *;
        location / {
          default_type text/plain;
          return 200 "Web AT www.f5bnk.com $server_name\n$remote_addr:$remote_port-->$server_addr:$server_port\n";
        }
      }
    }
